### ISSUE TITLE
Confused about <conf>

### ISSUE THREAD

**Issue by zhaoqxu** [richemslie/ggplearn#3]
In `doc/install.rst`, you mentioned the code below:
```
python server.py <conf>
python worker.py <conf>
```
Could you please elaborate on `<conf>`? Like giving some examples about the specific configurations or parameters. I'm really confused about how to start training the model after getting all the installation down. Thanks in advance!

**Comment by richemslie** [comment]
I'm in the process of rationalizing the configuration (lots of cruft over time).  I'll be done in a couple of days, and will add provide some examples/defaults to get going (and hopefully some step by step instructions).

In the meantime, an (albeit not very helpful) answer is to have a look in src/ggpzero/def/confs.py.  I also added some temporary examples in confs/

**Comment by zhaoqxu** [comment]
Thanks for your help

**Comment by richemslie** [comment]
To create a default config for server (using breakthroughSmall and generation name : "genx"):

$ python server.py -c breakthroughSmall genx > genx.conf

To create a default config for worker:
$ python worker.py -c > w.conf
