### ISSUE TITLE
Two tiny problems when compiling src/cpp

### ISSUE THREAD

**Issue by zhaoqxu** [richemslie/ggplearn#5]
There are two tiny problems when I tried to compile the code:

1.  Since we run the python in a virtual environment, it couldn't locate where the numpy is, so the problem below appears:
```
ggpzero_interface.cpp:4:10: fatal error: 'numpy/arrayobject.h' file not found
```
One way is to make a link:
```
ln -s /root/ggpzero/galvanise_zero/ggpzero/lib/python2.7/site-packages/numpy/core/include/numpy numpy
```

2.  It seems that you forget `#include <algorithm>` in evlauator.cpp, so the error below appears. When I add the line, the code compiled successfully. 
```
puct2/evaluator.cpp:244:10:`` error: no member named 'sort' in namespace 'std'
```

**Comment by richemslie** [comment]
1.  I've seen the same error when I ran on AWS.  I don't know of a clean solution.  One idea was to
add
`$ python -c "from distutils.sysconfig import get_python_lib ; print get_python_lib() + /numpy/include/core'"   `
to the INCLUDE_PATHS in the makefile.
2.  Thanks, will add it.
