### ISSUE TITLE
How to install that under windows OS?

### ISSUE THREAD

**Issue by htomtom** [richemslie/ggplearn#7]
How to install the project under windows os? Or how to install that on anaconda environment?
I have an anaconda environment with tensorflow+python, but I can not install GGPLib. There is no binary package. Is there any detailed guidance?

**Comment by richemslie** [comment]
Sorry, I am not acquainted with modern Windows OS unfortunately, I wouldn't know where to start with how to compile the C++ code.  There are some vague instructions to install under Linux, and I am in the progress of updating them and writing docs in general.
My only offer of advice would be to use a Virtual Machine, or dual boot with Linux.  Perhaps if (ever) the projects acquires users other than me, someone with more expertise can offer to try compile on Windows or create a binary package.

**Comment by htomtom** [comment]
Thanks for your advice. It may be effective to follow your proposals. If possible, I will try somtime.
